if(EXISTS "/home/sgilbert/repos/factorama/build2/integration_test-b12d07c_tests.cmake")
  include("/home/sgilbert/repos/factorama/build2/integration_test-b12d07c_tests.cmake")
else()
  add_test(integration_test_NOT_BUILT-b12d07c integration_test_NOT_BUILT-b12d07c)
endif()
