add_test( BasicResidualSanityTest /home/sgilbert/repos/factorama/build2/unit_test BasicResidualSanityTest  )
set_tests_properties( BasicResidualSanityTest PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( InverseRangeFactorSanityTest /home/sgilbert/repos/factorama/build2/unit_test InverseRangeFactorSanityTest  )
set_tests_properties( InverseRangeFactorSanityTest PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[PosePositionPriorFactor: dimensions and residual]==] /home/sgilbert/repos/factorama/build2/unit_test [==[PosePositionPriorFactor: dimensions and residual]==]  )
set_tests_properties( [==[PosePositionPriorFactor: dimensions and residual]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[GenericPriorFactor: dimensions and residual with LandmarkVariable]==] /home/sgilbert/repos/factorama/build2/unit_test [==[GenericPriorFactor: dimensions and residual with LandmarkVariable]==]  )
set_tests_properties( [==[GenericPriorFactor: dimensions and residual with LandmarkVariable]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[BearingObservationFactor: analytical Jacobian matches numerical]==] /home/sgilbert/repos/factorama/build2/unit_test [==[BearingObservationFactor: analytical Jacobian matches numerical]==]  )
set_tests_properties( [==[BearingObservationFactor: analytical Jacobian matches numerical]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[InverseRangeBearingFactor: analytical Jacobian matches numerical]==] /home/sgilbert/repos/factorama/build2/unit_test [==[InverseRangeBearingFactor: analytical Jacobian matches numerical]==]  )
set_tests_properties( [==[InverseRangeBearingFactor: analytical Jacobian matches numerical]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[SO(3) exponential and logarithmic maps round trip]==] /home/sgilbert/repos/factorama/build2/unit_test [==[SO(3) exponential and logarithmic maps round trip]==]  )
set_tests_properties( [==[SO(3) exponential and logarithmic maps round trip]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[SO(3) ExpMap produces orthonormal matrix]==] /home/sgilbert/repos/factorama/build2/unit_test [==[SO(3) ExpMap produces orthonormal matrix]==]  )
set_tests_properties( [==[SO(3) ExpMap produces orthonormal matrix]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[SO(3) ExpMap/LogMap π-rotation edge cases]==] /home/sgilbert/repos/factorama/build2/unit_test [==[SO(3) ExpMap/LogMap π-rotation edge cases]==]  )
set_tests_properties( [==[SO(3) ExpMap/LogMap π-rotation edge cases]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[SO(3) near-zero rotation is stable]==] /home/sgilbert/repos/factorama/build2/unit_test [==[SO(3) near-zero rotation is stable]==]  )
set_tests_properties( [==[SO(3) near-zero rotation is stable]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[SO(3) LogMap behaves near 180 degrees]==] /home/sgilbert/repos/factorama/build2/unit_test [==[SO(3) LogMap behaves near 180 degrees]==]  )
set_tests_properties( [==[SO(3) LogMap behaves near 180 degrees]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[PoseOrientationBetweenFactor residual and jacobian numeric check]==] /home/sgilbert/repos/factorama/build2/unit_test [==[PoseOrientationBetweenFactor residual and jacobian numeric check]==]  )
set_tests_properties( [==[PoseOrientationBetweenFactor residual and jacobian numeric check]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[PoseVariable apply_increment]==] /home/sgilbert/repos/factorama/build2/unit_test [==[PoseVariable apply_increment]==]  )
set_tests_properties( [==[PoseVariable apply_increment]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[RotationVariable apply_increment]==] /home/sgilbert/repos/factorama/build2/unit_test [==[RotationVariable apply_increment]==]  )
set_tests_properties( [==[RotationVariable apply_increment]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[GenericBetweenFactor residuals and jacobians with LandmarkVariable]==] /home/sgilbert/repos/factorama/build2/unit_test [==[GenericBetweenFactor residuals and jacobians with LandmarkVariable]==]  )
set_tests_properties( [==[GenericBetweenFactor residuals and jacobians with LandmarkVariable]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[PosePositionBetweenFactor computes correct residuals and jacobians]==] /home/sgilbert/repos/factorama/build2/unit_test [==[PosePositionBetweenFactor computes correct residuals and jacobians]==]  )
set_tests_properties( [==[PosePositionBetweenFactor computes correct residuals and jacobians]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[PosePositionPriorFactor: comprehensive behavior tests]==] /home/sgilbert/repos/factorama/build2/unit_test [==[PosePositionPriorFactor: comprehensive behavior tests]==]  )
set_tests_properties( [==[PosePositionPriorFactor: comprehensive behavior tests]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[PosePositionPriorFactor: analytical vs numerical Jacobians]==] /home/sgilbert/repos/factorama/build2/unit_test [==[PosePositionPriorFactor: analytical vs numerical Jacobians]==]  )
set_tests_properties( [==[PosePositionPriorFactor: analytical vs numerical Jacobians]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[PoseOrientationPriorFactor: analytical vs numerical Jacobians]==] /home/sgilbert/repos/factorama/build2/unit_test [==[PoseOrientationPriorFactor: analytical vs numerical Jacobians]==]  )
set_tests_properties( [==[PoseOrientationPriorFactor: analytical vs numerical Jacobians]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[Variable clone() method behaves correctly]==] /home/sgilbert/repos/factorama/build2/unit_test [==[Variable clone() method behaves correctly]==]  )
set_tests_properties( [==[Variable clone() method behaves correctly]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[FactorGraph apply_increment]==] /home/sgilbert/repos/factorama/build2/unit_test [==[FactorGraph apply_increment]==]  )
set_tests_properties( [==[FactorGraph apply_increment]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[FactorGraph ID Collision Detection]==] /home/sgilbert/repos/factorama/build2/unit_test [==[FactorGraph ID Collision Detection]==]  )
set_tests_properties( [==[FactorGraph ID Collision Detection]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[BearingProjectionFactor2D: Basic functionality and residual computation]==] /home/sgilbert/repos/factorama/build2/unit_test [==[BearingProjectionFactor2D: Basic functionality and residual computation]==]  )
set_tests_properties( [==[BearingProjectionFactor2D: Basic functionality and residual computation]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[BearingProjectionFactor2D: Jacobian accuracy against numerical differentiation]==] /home/sgilbert/repos/factorama/build2/unit_test [==[BearingProjectionFactor2D: Jacobian accuracy against numerical differentiation]==]  )
set_tests_properties( [==[BearingProjectionFactor2D: Jacobian accuracy against numerical differentiation]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[BearingProjectionFactor2D: Edge case handling for small alpha]==] /home/sgilbert/repos/factorama/build2/unit_test [==[BearingProjectionFactor2D: Edge case handling for small alpha]==]  )
set_tests_properties( [==[BearingProjectionFactor2D: Edge case handling for small alpha]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
add_test( [==[BearingProjectionFactor2D: Integration test with optimization convergence]==] /home/sgilbert/repos/factorama/build2/unit_test [==[BearingProjectionFactor2D: Integration test with optimization convergence]==]  )
set_tests_properties( [==[BearingProjectionFactor2D: Integration test with optimization convergence]==] PROPERTIES WORKING_DIRECTORY /home/sgilbert/repos/factorama/build2 SKIP_RETURN_CODE 4)
set( unit_test_TESTS BasicResidualSanityTest InverseRangeFactorSanityTest [==[PosePositionPriorFactor: dimensions and residual]==] [==[GenericPriorFactor: dimensions and residual with LandmarkVariable]==] [==[BearingObservationFactor: analytical Jacobian matches numerical]==] [==[InverseRangeBearingFactor: analytical Jacobian matches numerical]==] [==[SO(3) exponential and logarithmic maps round trip]==] [==[SO(3) ExpMap produces orthonormal matrix]==] [==[SO(3) ExpMap/LogMap π-rotation edge cases]==] [==[SO(3) near-zero rotation is stable]==] [==[SO(3) LogMap behaves near 180 degrees]==] [==[PoseOrientationBetweenFactor residual and jacobian numeric check]==] [==[PoseVariable apply_increment]==] [==[RotationVariable apply_increment]==] [==[GenericBetweenFactor residuals and jacobians with LandmarkVariable]==] [==[PosePositionBetweenFactor computes correct residuals and jacobians]==] [==[PosePositionPriorFactor: comprehensive behavior tests]==] [==[PosePositionPriorFactor: analytical vs numerical Jacobians]==] [==[PoseOrientationPriorFactor: analytical vs numerical Jacobians]==] [==[Variable clone() method behaves correctly]==] [==[FactorGraph apply_increment]==] [==[FactorGraph ID Collision Detection]==] [==[BearingProjectionFactor2D: Basic functionality and residual computation]==] [==[BearingProjectionFactor2D: Jacobian accuracy against numerical differentiation]==] [==[BearingProjectionFactor2D: Edge case handling for small alpha]==] [==[BearingProjectionFactor2D: Integration test with optimization convergence]==])
