name: Build wheels

on:
  push:
    tags: ['v*']  # Trigger on version tags
  workflow_dispatch:  # Manual trigger

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          # Build CPython 3.8–3.12 for all platforms
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          # Skip PyPy and 32-bit builds
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686"
          CIBW_VERBOSE: "1"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  upload_to_release:
    name: Upload wheels to release
    needs: build_wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          
      - name: Create platform archives
        run: |
          cd dist/
          for platform in wheels-*; do
            zip -r "../${platform}.zip" "$platform/"
          done
          ls -la ../*.zip
          
      - name: Upload archives to release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"