name: Build wheels

on:
  push:
    tags: ['v*']  # Trigger on version tags
  workflow_dispatch:  # Manual trigger

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          # Build CPython 3.8–3.12 for all platforms
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          # Skip PyPy and 32-bit builds
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686"
          CIBW_VERBOSE: "1"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl