name: Build wheels

on:
  push:
    tags: ['v*']  # Trigger on version tags
  workflow_dispatch:  # Manual trigger

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]   # windows-latest, ubuntu-latest, macos-latest later if desired
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD: "cp38-win_amd64 cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64"
          CIBW_SKIP: "pp* *-win32"
          CIBW_VERBOSE: "1"  # Useful for debug: prints build environment info
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl